-- Question 1: Basic statistics about patients within each race

SELECT 
  r.RACE_DESCRIPTION AS "Race",
  COUNT(DISTINCT p.PATIENT_ID) AS "Total Patients",
  COUNT(DISTINCT CASE WHEN g.GENDER_DESCRIPTION = 'Male' THEN p.PATIENT_ID END) AS "Male Patients",
  COUNT(DISTINCT CASE WHEN g.GENDER_DESCRIPTION = 'Female' THEN p.PATIENT_ID END) AS "Female Patients",
  ROUND(COUNT(CASE WHEN ms.MARITAL_STATUS_DESCRIPTION = 'Married' AND e.ETHNICITY_DESCRIPTION != 'Hispanic' THEN 1 END) / COUNT(p.PATIENT_ID) * 100) AS "Married and Non-Hispanic %"
FROM NITRE_PATIENT p
JOIN NITRE_PATIENT_IMMUNIZATION pv ON p.PATIENT_ID = pv.PATIENT_ID
JOIN NITRE_IMMUNIZATION v ON pv.IMMUNIZATION_CODE = v.IMMUNIZATION_CODE
JOIN NITRE_CITY nc ON p.LIVING_PLACE_COUNTRY_ID = nc.COUNTRY_ID
JOIN NITRE_COUNTY co ON nc.COUNTY_ID = co.COUNTY_ID
JOIN NITRE_RACE r ON p.RACE_ID = r.RACE_ID
JOIN NITRE_GENDER g ON p.GENDER_ID = g.GENDER_ID
JOIN NITRE_MARITAL_STATUS ms ON p.MARITAL_STATUS_ID = ms.MARITAL_STATUS_ID
JOIN NITRE_ETHNICITY e ON p.ETHNICITY_ID = e.ETHNICITY_ID
WHERE co.COUNTY_NAME = 'Middlesex County' AND v.IMMUNIZATION_DESCRIPTION IN ('Hep A', 'Hep B')
GROUP BY r.RACE_DESCRIPTION, co.COUNTY_ID, co.STATE_ID, co.COUNTRY_ID;

-- Question 2: Medication with highest total cost within each race

SELECT M.RACE_DESCRIPTION, M.MEDICATION_CODE, SUBSTR(M.MEDICATION_DESCRIPTION, 1, INSTR(M.MEDICATION_DESCRIPTION, ' ') - 1) AS MEDICATION_NAME, M.TOTAL_COST AS HIGHEST_TOTAL_COST
FROM (
    SELECT 
        NR.RACE_DESCRIPTION, 
        MED.MEDICATION_CODE,
        MD.MEDICATION_DESCRIPTION,
        SUM(MED.TOTAL_COST) AS TOTAL_COST
    FROM NITRE_PATIENT P
    JOIN NITRE_PATIENT_MEDICATION MED ON MED.PATIENT_ID = P.PATIENT_ID
    JOIN NITRE_MEDICATION MD ON MED.MEDICATION_CODE = MD.MEDICATION_CODE
    JOIN NITRE_RACE NR ON P.RACE_ID = NR.RACE_ID
    JOIN NITRE_PATIENT_IMMUNIZATION IMM ON IMM.PATIENT_ID = P.PATIENT_ID
    JOIN NITRE_CITY nc ON p.LIVING_PLACE_COUNTRY_ID = nc.COUNTRY_ID
    JOIN NITRE_COUNTY co ON nc.COUNTY_ID = co.COUNTY_ID
    JOIN NITRE_IMMUNIZATION v ON IMM.IMMUNIZATION_CODE = v.IMMUNIZATION_CODE
    WHERE co.COUNTY_NAME = 'Middlesex County'
        AND v.IMMUNIZATION_DESCRIPTION IN ('Hep A', 'Hep B')
    GROUP BY NR.RACE_DESCRIPTION, MED.MEDICATION_CODE, MD.MEDICATION_DESCRIPTION
) M
JOIN (
    SELECT RACE_DESCRIPTION, MAX(TOTAL_COST) AS MAX_TOTAL_COST
    FROM (
        SELECT 
            NR.RACE_DESCRIPTION, 
            MED.MEDICATION_CODE,
            SUM(MED.TOTAL_COST) AS TOTAL_COST
        FROM NITRE_PATIENT P
        JOIN NITRE_PATIENT_MEDICATION MED ON MED.PATIENT_ID = P.PATIENT_ID
        JOIN NITRE_MEDICATION MD ON MED.MEDICATION_CODE = MD.MEDICATION_CODE
        JOIN NITRE_RACE NR ON P.RACE_ID = NR.RACE_ID
        JOIN NITRE_PATIENT_IMMUNIZATION IMM ON IMM.PATIENT_ID = P.PATIENT_ID
        JOIN NITRE_CITY nc ON p.LIVING_PLACE_COUNTRY_ID = nc.COUNTRY_ID
        JOIN NITRE_COUNTY co ON nc.COUNTY_ID = co.COUNTY_ID
        JOIN NITRE_IMMUNIZATION v ON IMM.IMMUNIZATION_CODE = v.IMMUNIZATION_CODE
        WHERE co.COUNTY_NAME = 'Middlesex County'
            AND v.IMMUNIZATION_DESCRIPTION IN ('Hep A', 'Hep B')
        GROUP BY NR.RACE_DESCRIPTION, MED.MEDICATION_CODE
    ) C
    GROUP BY RACE_DESCRIPTION
) T ON M.RACE_DESCRIPTION = T.RACE_DESCRIPTION AND M.TOTAL_COST = T.MAX_TOTAL_COST;

-- Question 3: Reason for procedures with highest total base cost within each race

SELECT
    NR.RACE_DESCRIPTION,
    nre.REASON_CODE,
    nre.REASON_DESCRIPTION,
    SUM(pr.BASE_COST) AS TOTAL_BASE_COST
FROM
    NITRE_PATIENT p
    JOIN NITRE_PATIENT_PROCEDURE pr ON p.PATIENT_ID = pr.PATIENT_ID
    JOIN NITRE_REASON nre ON pr.REASON_CODE = nre.REASON_CODE
    JOIN NITRE_RACE NR ON P.RACE_ID = NR.RACE_ID
    JOIN NITRE_CITY nc ON p.LIVING_PLACE_COUNTRY_ID = nc.COUNTRY_ID
    JOIN NITRE_COUNTY co ON nc.COUNTY_ID = co.COUNTY_ID
    JOIN NITRE_PATIENT_IMMUNIZATION IMM ON IMM.PATIENT_ID = P.PATIENT_ID
    JOIN NITRE_IMMUNIZATION v ON IMM.IMMUNIZATION_CODE = v.IMMUNIZATION_CODE
WHERE co.COUNTY_NAME = 'Middlesex County'
    AND NR.RACE_DESCRIPTION IS NOT NULL
    AND p.GENDER_ID IS NOT NULL
    AND v.IMMUNIZATION_DESCRIPTION IN ('Hep A', 'Hep B')
    AND nre.REASON_DESCRIPTION NOT LIKE '%pregnancy%'
GROUP BY
    NR.RACE_DESCRIPTION,
    nre.REASON_CODE,
    nre.REASON_DESCRIPTION
HAVING
    SUM(pr.BASE_COST) = (
        SELECT MAX(total_base_cost)
        FROM (
            SELECT
            NR.RACE_DESCRIPTION,
            nre.REASON_CODE,
            nre.REASON_DESCRIPTION,
            SUM(pr.BASE_COST) AS total_base_cost
            FROM
            NITRE_PATIENT p
            JOIN NITRE_PATIENT_PROCEDURE pr ON p.PATIENT_ID = pr.PATIENT_ID
            JOIN NITRE_RACE NR ON P.RACE_ID = NR.RACE_ID
            JOIN NITRE_CITY nc ON p.LIVING_PLACE_COUNTRY_ID = nc.COUNTRY_ID
            JOIN NITRE_COUNTY co ON nc.COUNTY_ID = co.COUNTY_ID
            JOIN NITRE_REASON nre ON pr.REASON_CODE = nre.REASON_CODE
            JOIN NITRE_PATIENT_IMMUNIZATION IMM ON IMM.PATIENT_ID = P.PATIENT_ID
            JOIN NITRE_IMMUNIZATION v ON IMM.IMMUNIZATION_CODE = v.IMMUNIZATION_CODE
            WHERE co.COUNTY_NAME = 'Middlesex County'
                AND NR.RACE_DESCRIPTION IS NOT NULL
                AND p.GENDER_ID IS NOT NULL
                AND v.IMMUNIZATION_DESCRIPTION IN ('Hep A', 'Hep B')
                AND nre.REASON_DESCRIPTION NOT LIKE '%pregnancy%'
        GROUP BY
        NR.RACE_DESCRIPTION,
        nre.REASON_CODE,
        nre.REASON_DESCRIPTION)
        WHERE RACE_DESCRIPTION = NR.RACE_DESCRIPTION)
ORDER BY
NR.RACE_DESCRIPTION ASC,
TOTAL_BASE_COST DESC;

-- Question 4: Merged report of all previous queries

SELECT 
    Q1.RACE_DESCRIPTION, 
    Q1.TOTAL_PATIENTS, 
    Q1.MALE_PATIENTS, 
    Q1.FEMALE_PATIENTS, 
    Q1.NON_HISPANIC_MARRIED_PERCENTAGE, 
    Q2.MEDICATION_NAME,
    Q2.HIGHEST_TOTAL_COST,
    Q3.REASON_CODE,
    Q3.REASON_DESCRIPTION,
    Q3.TOTAL_BASE_COST
FROM 
    (SELECT 
        r.RACE_DESCRIPTION, 
        COUNT(DISTINCT p.PATIENT_ID) AS TOTAL_PATIENTS, 
        COUNT(DISTINCT CASE WHEN g.GENDER_DESCRIPTION = 'Male' THEN p.PATIENT_ID END) AS MALE_PATIENTS, 
        COUNT(DISTINCT CASE WHEN g.GENDER_DESCRIPTION = 'Female' THEN p.PATIENT_ID END) AS FEMALE_PATIENTS, 
        ROUND(COUNT(CASE WHEN ms.MARITAL_STATUS_DESCRIPTION = 'Married' AND e.ETHNICITY_DESCRIPTION != 'Hispanic' THEN 1 END) / COUNT(p.PATIENT_ID) * 100) AS NON_HISPANIC_MARRIED_PERCENTAGE 
    FROM 
        NITRE_PATIENT p 
        JOIN NITRE_PATIENT_IMMUNIZATION i ON p.PATIENT_ID = i.PATIENT_ID 
        JOIN NITRE_IMMUNIZATION v ON i.IMMUNIZATION_CODE = v.IMMUNIZATION_CODE
        JOIN NITRE_CITY nc ON p.LIVING_PLACE_COUNTRY_ID = nc.COUNTRY_ID
        JOIN NITRE_COUNTY co ON nc.COUNTY_ID = co.COUNTY_ID
        JOIN NITRE_RACE r ON p.RACE_ID = r.RACE_ID
        JOIN NITRE_GENDER g ON p.GENDER_ID = g.GENDER_ID
        JOIN NITRE_MARITAL_STATUS ms ON p.MARITAL_STATUS_ID = ms.MARITAL_STATUS_ID
        JOIN NITRE_ETHNICITY e ON p.ETHNICITY_ID = e.ETHNICITY_ID
    WHERE 
        co.COUNTY_NAME = 'Middlesex County' 
        AND v.IMMUNIZATION_DESCRIPTION IN ('Hep A', 'Hep B')
    GROUP BY 
        r.RACE_DESCRIPTION) Q1
JOIN 
    (SELECT M.RACE_DESCRIPTION, M.MEDICATION_CODE, SUBSTR(M.MEDICATION_DESCRIPTION, 1, INSTR(M.MEDICATION_DESCRIPTION, ' ') - 1) AS MEDICATION_NAME, M.TOTAL_COST AS HIGHEST_TOTAL_COST
    FROM (
        SELECT 
            NR.RACE_DESCRIPTION, 
            MED.MEDICATION_CODE,
            MD.MEDICATION_DESCRIPTION,
            SUM(MED.TOTAL_COST) AS TOTAL_COST
        FROM NITRE_PATIENT P
        JOIN NITRE_PATIENT_MEDICATION MED ON MED.PATIENT_ID = P.PATIENT_ID
        JOIN NITRE_MEDICATION MD ON MED.MEDICATION_CODE = MD.MEDICATION_CODE
        JOIN NITRE_RACE NR ON P.RACE_ID = NR.RACE_ID
        JOIN NITRE_PATIENT_IMMUNIZATION IMM ON IMM.PATIENT_ID = P.PATIENT_ID
        JOIN NITRE_CITY nc ON p.LIVING_PLACE_COUNTRY_ID = nc.COUNTRY_ID
        JOIN NITRE_COUNTY co ON nc.COUNTY_ID = co.COUNTY_ID
        JOIN NITRE_IMMUNIZATION v ON IMM.IMMUNIZATION_CODE = v.IMMUNIZATION_CODE
        WHERE co.COUNTY_NAME = 'Middlesex County'
            AND v.IMMUNIZATION_DESCRIPTION IN ('Hep A', 'Hep B')
        GROUP BY NR.RACE_DESCRIPTION, MED.MEDICATION_CODE, MD.MEDICATION_DESCRIPTION
    ) M
    JOIN (
        SELECT RACE_DESCRIPTION, MAX(TOTAL_COST) AS MAX_TOTAL_COST
        FROM (
            SELECT 
                NR.RACE_DESCRIPTION, 
                MED.MEDICATION_CODE,
                SUM(MED.TOTAL_COST) AS TOTAL_COST
            FROM NITRE_PATIENT P
            JOIN NITRE_PATIENT_MEDICATION MED ON MED.PATIENT_ID = P.PATIENT_ID
            JOIN NITRE_MEDICATION MD ON MED.MEDICATION_CODE = MD.MEDICATION_CODE
            JOIN NITRE_RACE NR ON P.RACE_ID = NR.RACE_ID
            JOIN NITRE_PATIENT_IMMUNIZATION IMM ON IMM.PATIENT_ID = P.PATIENT_ID
            JOIN NITRE_CITY nc ON p.LIVING_PLACE_COUNTRY_ID = nc.COUNTRY_ID
            JOIN NITRE_COUNTY co ON nc.COUNTY_ID = co.COUNTY_ID
            JOIN NITRE_IMMUNIZATION v ON IMM.IMMUNIZATION_CODE = v.IMMUNIZATION_CODE
            WHERE co.COUNTY_NAME = 'Middlesex County'
                AND v.IMMUNIZATION_DESCRIPTION IN ('Hep A', 'Hep B')
            GROUP BY NR.RACE_DESCRIPTION, MED.MEDICATION_CODE
        ) C
        GROUP BY RACE_DESCRIPTION
    ) T ON M.RACE_DESCRIPTION = T.RACE_DESCRIPTION AND M.TOTAL_COST = T.MAX_TOTAL_COST) Q2 ON Q1.RACE_DESCRIPTION = Q2.RACE_DESCRIPTION
JOIN 
    (SELECT
        NR.RACE_DESCRIPTION,
        nre.REASON_CODE,
        nre.REASON_DESCRIPTION,
        SUM(pr.BASE_COST) AS TOTAL_BASE_COST
    FROM
        NITRE_PATIENT p
        JOIN NITRE_PATIENT_PROCEDURE pr ON p.PATIENT_ID = pr.PATIENT_ID
        JOIN NITRE_REASON nre ON pr.REASON_CODE = nre.REASON_CODE
        JOIN NITRE_RACE NR ON P.RACE_ID = NR.RACE_ID
        JOIN NITRE_CITY nc ON p.LIVING_PLACE_COUNTRY_ID = nc.COUNTRY_ID
        JOIN NITRE_COUNTY co ON nc.COUNTY_ID = co.COUNTY_ID
        JOIN NITRE_PATIENT_IMMUNIZATION IMM ON IMM.PATIENT_ID = P.PATIENT_ID
        JOIN NITRE_IMMUNIZATION v ON IMM.IMMUNIZATION_CODE = v.IMMUNIZATION_CODE
    WHERE co.COUNTY_NAME = 'Middlesex County'
        AND NR.RACE_DESCRIPTION IS NOT NULL
        AND p.GENDER_