-- Project: Synthetic Clinical Patient Database 


-- REPORTS:  prepare each report below using MITRE_ and NITRE_ tables only, but separately.

-- ●	In ALL reports you MUST consider:
-- o	patients living in “Middlesex County” who have taken any of the “Hep A” or “Hep B” vaccines ONLY
-- ●	In all reports you will be providing information regarding each “race”.
-- ●	Each SQL must be complete and given by one SQL statement only (SELECT)
-- o	but you can use as many JOINs and subqueries as needed
-- ●	DO NOT use “WITH”
-- o	your SQL statement MUST start with SELECT
-- ●	DO NOT create VIEWs

-- Question 1	Within each race, provide basic statistics about the number of patients:
-- ●	Total number of patients.
-- ●	Number of male patients.
-- ●	Number of female patients.
-- ●	The percentage of patients that are married and non- Hispanic at the same time.
-- o	0-100%, no decimals
-- * Don’t forget to consider the core filter for all reports


-- SQL (MITRE):	

SELECT
  RACE,
  COUNT(*) AS TOTAL_PATIENTS,
  SUM(CASE WHEN GENDER = 'M' THEN 1 ELSE 0 END) AS MALE_PATIENTS,
  SUM(CASE WHEN GENDER = 'F' THEN 1 ELSE 0 END) AS FEMALE_PATIENTS,
  ROUND(100 * SUM(CASE WHEN MARITAL_STATUS = 'M' AND ETHNICITY = 'nonhispanic' THEN 1 ELSE 0 END) / COUNT(*)) AS NON_HISPANIC_MARRIED_PERCENTAGE
FROM
  vrm32.MITRE_PATIENT p
  INNER JOIN vrm32.MITRE_PATIENT_IMMUNIZATION i ON p.PATIENT_ID = i.PATIENT_ID
WHERE
  COUNTY = 'Middlesex County'
  AND IMMUNIZATION_CODE IN ('52', '43', '83', '8')
GROUP BY
  RACE;


-- SQL (NITRE):	

SELECT r.RACE_DESCRIPTION AS "Race",
COUNT(DISTINCT p.PATIENT_ID) AS "Total Patients",
COUNT(DISTINCT CASE WHEN p.GENDER_ID = 'M' THEN p.PATIENT_ID END) AS "Male Patients",
COUNT(DISTINCT CASE WHEN p.GENDER_ID = 'F' THEN p.PATIENT_ID END) AS "Female Patients",
ROUND(COUNT(CASE WHEN p.MARITAL_STATUS_ID = 'M' AND p.ETHNICITY_ID != 1 THEN 1 END) / COUNT(p.PATIENT_ID) * 100) AS "Married and Non-Hispanic %"
FROM vrm32.NITRE_PATIENT p
JOIN vrm32.NITRE_PATIENT_IMMUNIZATION pv ON p.PATIENT_ID = pv.PATIENT_ID
JOIN vrm32.NITRE_IMMUNIZATION v ON pv.IMMUNIZATION_CODE = v.IMMUNIZATION_CODE
JOIN vrm32.NITRE_CITY nc ON p.LIVING_PLACE_COUNTRY_ID = nc.COUNTRY_ID
JOIN vrm32.NITRE_COUNTY co ON nc.COUNTY_ID = co.COUNTY_ID
JOIN vrm32.NITRE_RACE r ON p.RACE_ID = r.RACE_ID
WHERE co.COUNTY_ID = 9 AND v.IMMUNIZATION_CODE IN (43,52,8,83)
GROUP BY r.RACE_DESCRIPTION, co.COUNTY_ID, co.STATE_ID, co.COUNTRY_ID;

-- Result	 
-- Comments	The output from NITRE includes the ‘other’ and ‘native’ races too. All the values in the output are different for MITRE and NITRE. It may be because of the differences in constraints for both. The normalized data model of NITRE_ has different values in its look up table compared to MITRE_ 
-- For example: 
-- In MITRE, the Total Patients for Asian race is 40 compared to 44 in NITRE.
-- In MITRE, the percentage of patients that are married and non- Hispanic at the same time for white race is 28 compared to 3 in NITRE.




-- Question 2	Within each race, report the medication that achieved the highest total cost, including:
-- ●	Medication Code
-- ●	Medication Description (first word only)
-- ●	Total Cost
-- * Don’t forget to consider the core filter for all reports

-- SQL (MITRE):	

SELECT M.RACE, M.MEDICATION_CODE, SUBSTR(M.MEDICATION_DESCRIPTION, 1, INSTR(M.MEDICATION_DESCRIPTION, ' ') - 1) AS MEDICATION_NAME, M.TOTAL_COST AS HIGHEST_TOTAL_COST
FROM (
    SELECT 
        P.RACE, 
        MED.MEDICATION_CODE,
        MED.MEDICATION_DESCRIPTION,
        SUM(MED.TOTAL_COST) AS TOTAL_COST
    FROM vrm32.MITRE_PATIENT P
    JOIN vrm32.MITRE_PATIENT_MEDICATION MED ON MED.PATIENT_ID = P.PATIENT_ID
    JOIN vrm32.MITRE_PATIENT_IMMUNIZATION IMM ON IMM.PATIENT_ID = P.PATIENT_ID
    WHERE P.COUNTY = 'Middlesex County'
        AND IMM.IMMUNIZATION_CODE IN ('52', '43', '83', '8')
    GROUP BY P.RACE, MED.MEDICATION_CODE, MED.MEDICATION_DESCRIPTION
) M
JOIN (
    SELECT RACE, MAX(TOTAL_COST) AS MAX_TOTAL_COST
    FROM (
        SELECT 
            P.RACE, 
            MED.MEDICATION_CODE,
            SUM(MED.TOTAL_COST) AS TOTAL_COST
        FROM vrm32.MITRE_PATIENT P
        JOIN vrm32.MITRE_PATIENT_MEDICATION MED ON MED.PATIENT_ID = P.PATIENT_ID
        JOIN vrm32.MITRE_PATIENT_IMMUNIZATION IMM ON IMM.PATIENT_ID = P.PATIENT_ID
        WHERE P.COUNTY = 'Middlesex County'
            AND IMM.IMMUNIZATION_CODE IN ('52', '43', '83', '8')
        GROUP BY P.RACE, MED.MEDICATION_CODE
    ) C
    GROUP BY RACE
) T ON M.RACE = T.RACE AND M.TOTAL_COST = T.MAX_TOTAL_COST;
	 
-- SQL (NITRE):	

SELECT M.RACE_DESCRIPTION, M.MEDICATION_CODE, SUBSTR(M.MEDICATION_DESCRIPTION, 1, INSTR(M.MEDICATION_DESCRIPTION, ' ') - 1) AS MEDICATION_NAME, M.TOTAL_COST AS HIGHEST_TOTAL_COST
FROM (
    SELECT 
        NR.RACE_DESCRIPTION, 
        MED.MEDICATION_CODE,
        MD.MEDICATION_DESCRIPTION,
        SUM(MED.TOTAL_COST) AS TOTAL_COST
    FROM vrm32.NITRE_PATIENT P
    JOIN vrm32.NITRE_PATIENT_MEDICATION MED ON MED.PATIENT_ID = P.PATIENT_ID
    JOIN vrm32.NITRE_MEDICATION MD ON MED.MEDICATION_CODE = MD.MEDICATION_CODE
    JOIN vrm32.NITRE_RACE NR ON P.RACE_ID = NR.RACE_ID
    JOIN vrm32.NITRE_PATIENT_IMMUNIZATION IMM ON IMM.PATIENT_ID = P.PATIENT_ID
    JOIN vrm32.NITRE_CITY nc ON p.LIVING_PLACE_COUNTRY_ID = nc.COUNTRY_ID
    JOIN vrm32.NITRE_COUNTY co ON nc.COUNTY_ID = co.COUNTY_ID
    WHERE co.COUNTY_ID = 9
        AND IMM.IMMUNIZATION_CODE IN ('52', '43', '83', '8')
    GROUP BY NR.RACE_DESCRIPTION, MED.MEDICATION_CODE, MD.MEDICATION_DESCRIPTION
) M
JOIN (
    SELECT RACE_DESCRIPTION, MAX(TOTAL_COST) AS MAX_TOTAL_COST
    FROM (
        SELECT 
            NR.RACE_DESCRIPTION, 
            MED.MEDICATION_CODE,
            SUM(MED.TOTAL_COST) AS TOTAL_COST
        FROM vrm32.NITRE_PATIENT P
        JOIN vrm32.NITRE_PATIENT_MEDICATION MED ON MED.PATIENT_ID = P.PATIENT_ID
        JOIN vrm32.NITRE_MEDICATION MD ON MED.MEDICATION_CODE = MD.MEDICATION_CODE
        JOIN vrm32.NITRE_RACE NR ON P.RACE_ID = NR.RACE_ID
        JOIN vrm32.NITRE_PATIENT_IMMUNIZATION IMM ON IMM.PATIENT_ID = P.PATIENT_ID
        JOIN vrm32.NITRE_CITY nc ON p.LIVING_PLACE_COUNTRY_ID = nc.COUNTRY_ID
        JOIN vrm32.NITRE_COUNTY co ON nc.COUNTY_ID = co.COUNTY_ID
        WHERE co.COUNTY_ID = 9
            AND IMM.IMMUNIZATION_CODE IN ('52', '43', '83', '8')
        GROUP BY NR.RACE_DESCRIPTION, MED.MEDICATION_CODE
    ) C
    GROUP BY RACE_DESCRIPTION
) T ON M.RACE_DESCRIPTION = T.RACE_DESCRIPTION AND M.TOTAL_COST = T.MAX_TOTAL_COST;


-- Question 3	Within each race, report the reason for procedures with highest total base cost (but ignore any reason related to “pregnancy”), showing:
-- ●	Reason Code
-- ●	Reason Description
-- ●	Total of Base Cost
-- * Don’t forget to consider the core filter for all reports
-- SQL (MITRE):	

    SELECT
    p.RACE,
    pr.REASON_CODE,
    pr.REASON_DESCRIPTION,
    SUM(pr.BASE_COST) AS TOTAL_BASE_COST
FROM
    vrm32.MITRE_PATIENT p
    JOIN vrm32.MITRE_PATIENT_PROCEDURE pr ON p.PATIENT_ID = pr.PATIENT_ID
    
WHERE
    p.COUNTY = 'Middlesex County'
    AND p.RACE IS NOT NULL
    AND p.GENDER IS NOT NULL
    AND p.PATIENT_ID IN (
        SELECT i.PATIENT_ID
        FROM vrm32.MITRE_PATIENT_IMMUNIZATION i
        WHERE i.IMMUNIZATION_CODE IN ('52', '43', '83', '8')
    )
    AND pr.REASON_DESCRIPTION NOT LIKE '%pregnancy%'
GROUP BY
    p.RACE,
    pr.REASON_CODE,
    pr.REASON_DESCRIPTION
HAVING
    SUM(pr.BASE_COST) = (
        SELECT MAX(total_base_cost)
        FROM (
            SELECT
                p.RACE,
                pr.REASON_CODE,
                pr.REASON_DESCRIPTION,
                SUM(pr.BASE_COST) AS total_base_cost
            FROM
                vrm32.MITRE_PATIENT p
                JOIN vrm32.MITRE_PATIENT_PROCEDURE pr ON p.PATIENT_ID = pr.PATIENT_ID
            WHERE
                p.COUNTY = 'Middlesex County'
                AND p.RACE IS NOT NULL
                AND p.GENDER IS NOT NULL
                AND p.PATIENT_ID IN (
                    SELECT i.PATIENT_ID
                    FROM vrm32.MITRE_PATIENT_IMMUNIZATION i
                    WHERE i.IMMUNIZATION_CODE IN ('52', '43', '83', '8')
                )
                AND pr.REASON_DESCRIPTION NOT LIKE '%pregnancy%'
            GROUP BY
                p.RACE,
                pr.REASON_CODE,
                pr.REASON_DESCRIPTION
        )
        WHERE
            RACE = p.RACE
    )
ORDER BY
    p.RACE ASC,
    TOTAL_BASE_COST DESC;  
 

-- SQL (NITRE):	

    SELECT
    NR.RACE_DESCRIPTION,
    nre.REASON_CODE,
    nre.REASON_DESCRIPTION,
    SUM(pr.BASE_COST) AS TOTAL_BASE_COST
FROM
    vrm32.NITRE_PATIENT p
    JOIN vrm32.NITRE_PATIENT_PROCEDURE pr ON p.PATIENT_ID = pr.PATIENT_ID
    JOIN vrm32.NITRE_REASON nre ON pr.REASON_CODE = nre.REASON_CODE
    JOIN vrm32.NITRE_RACE NR ON P.RACE_ID = NR.RACE_ID
    JOIN vrm32.NITRE_CITY nc ON p.LIVING_PLACE_COUNTRY_ID = nc.COUNTRY_ID
    JOIN vrm32.NITRE_COUNTY co ON nc.COUNTY_ID = co.COUNTY_ID
WHERE co.COUNTY_ID = 9
    AND NR.RACE_DESCRIPTION IS NOT NULL
    AND p.GENDER_ID IS NOT NULL
    AND p.PATIENT_ID IN (
        SELECT i.PATIENT_ID
        FROM vrm32.NITRE_PATIENT_IMMUNIZATION i
        WHERE i.IMMUNIZATION_CODE IN ('52', '43', '83', '8')
        )
    AND nre.REASON_DESCRIPTION NOT LIKE '%pregnancy%'
    GROUP BY
    NR.RACE_DESCRIPTION,
    nre.REASON_CODE,
    nre.REASON_DESCRIPTION
    HAVING
    SUM(pr.BASE_COST) = (
        SELECT MAX(total_base_cost)
        FROM (
            SELECT
            NR.RACE_DESCRIPTION,
            nre.REASON_CODE,
            nre.REASON_DESCRIPTION,
            SUM(pr.BASE_COST) AS total_base_cost
            FROM
            vrm32.NITRE_PATIENT p
            JOIN vrm32.NITRE_PATIENT_PROCEDURE pr ON p.PATIENT_ID = pr.PATIENT_ID
            JOIN vrm32.NITRE_RACE NR ON P.RACE_ID = NR.RACE_ID
            JOIN vrm32.NITRE_CITY nc ON p.LIVING_PLACE_COUNTRY_ID = nc.COUNTRY_ID
            JOIN vrm32.NITRE_COUNTY co ON nc.COUNTY_ID = co.COUNTY_ID
            JOIN vrm32.NITRE_REASON nre ON pr.REASON_CODE = nre.REASON_CODE
            WHERE co.COUNTY_NAME = 'Middlesex County'
                AND NR.RACE_DESCRIPTION IS NOT NULL
                AND p.GENDER_ID IS NOT NULL
                AND p.PATIENT_ID IN (
                    SELECT i.PATIENT_ID
                    FROM vrm32.NITRE_PATIENT_IMMUNIZATION i
                    WHERE i.IMMUNIZATION_CODE IN ('52', '43', '83', '8')
                    )
                AND nre.REASON_DESCRIPTION NOT LIKE '%pregnancy%'
        GROUP BY
        NR.RACE_DESCRIPTION,
        nre.REASON_CODE,
        nre.REASON_DESCRIPTION)
        WHERE RACE_DESCRIPTION = NR.RACE_DESCRIPTION)
ORDER BY
NR.RACE_DESCRIPTION ASC,
TOTAL_BASE_COST DESC;

-- Question 4	Merge all previous reports in a single report, showing all columns from all reports for each race.
-- SQL (MITRE)	The query for combining queries 1 and 2:

SELECT 
  P.RACE,
  COUNT(*) AS TOTAL_PATIENTS,
  SUM(CASE WHEN P.GENDER = 'M' THEN 1 ELSE 0 END) AS MALE_PATIENTS,
  SUM(CASE WHEN P.GENDER = 'F' THEN 1 ELSE 0 END) AS FEMALE_PATIENTS,
  ROUND(100 * SUM(CASE WHEN P.MARITAL_STATUS = 'M' AND P.ETHNICITY = 'nonhispanic' THEN 1 ELSE 0 END) / COUNT(*)) AS NON_HISPANIC_MARRIED_PERCENTAGE,
  M.MEDICATION_CODE,
  SUBSTR(M.MEDICATION_DESCRIPTION, 1, INSTR(M.MEDICATION_DESCRIPTION, ' ') - 1) AS MEDICATION_NAME,
  M.TOTAL_COST AS HIGHEST_TOTAL_COST
FROM vrm32.MITRE_PATIENT P
JOIN vrm32.MITRE_PATIENT_IMMUNIZATION IMM ON IMM.PATIENT_ID = P.PATIENT_ID
LEFT JOIN (
  SELECT 
    P.RACE, 
    MED.MEDICATION_CODE,
    MED.MEDICATION_DESCRIPTION,
    SUM(MED.TOTAL_COST) AS TOTAL_COST
  FROM vrm32.MITRE_PATIENT P
  JOIN vrm32.MITRE_PATIENT_MEDICATION MED ON MED.PATIENT_ID = P.PATIENT_ID
  JOIN vrm32.MITRE_PATIENT_IMMUNIZATION IMM ON IMM.PATIENT_ID = P.PATIENT_ID
  WHERE P.COUNTY = 'Middlesex County'
    AND IMM.IMMUNIZATION_CODE IN ('52', '43', '83', '8')
  GROUP BY P.RACE, MED.MEDICATION_CODE, MED.MEDICATION_DESCRIPTION
) M ON P.RACE = M.RACE
JOIN (
  SELECT 
    RACE, 
    MAX(TOTAL_COST) AS MAX_TOTAL_COST
  FROM (
    SELECT 
      P.RACE, 
      MED.MEDICATION_CODE,
      SUM(MED.TOTAL_COST) AS TOTAL_COST
    FROM vrm32.MITRE_PATIENT P
    JOIN vrm32.MITRE_PATIENT_MEDICATION MED ON MED.PATIENT_ID = P.PATIENT_ID
    JOIN vrm32.MITRE_PATIENT_IMMUNIZATION IMM ON IMM.PATIENT_ID = P.PATIENT_ID
    WHERE P.COUNTY = 'Middlesex County'
      AND IMM.IMMUNIZATION_CODE IN ('52', '43', '83', '8')
    GROUP BY P.RACE, MED.MEDICATION_CODE
  ) C
  GROUP BY RACE
) T ON P.RACE = T.RACE AND M.TOTAL_COST = T.MAX_TOTAL_COST
WHERE P.COUNTY = 'Middlesex County'
  AND IMM.IMMUNIZATION_CODE IN ('52', '43', '83', '8')
GROUP BY 
  P.RACE, 
  M.MEDICATION_CODE, 
  M.MEDICATION_DESCRIPTION, 
  M.TOTAL_COST,
  T.RACE;



SELECT 
  Q1.RACE, 
  Q1.TOTAL_PATIENTS, 
  Q1.MALE_PATIENTS, 
  Q1.FEMALE_PATIENTS, 
  Q1.NON_HISPANIC_MARRIED_PERCENTAGE, 
  Q2.MEDICATION_NAME,
  Q2.HIGHEST_TOTAL_COST,
  Q3.REASON_CODE,
  Q3.REASON_DESCRIPTION,
  Q3.TOTAL_BASE_COST
FROM 
  (SELECT 
    RACE, 
    COUNT(*) AS TOTAL_PATIENTS, 
    SUM(CASE WHEN GENDER = 'M' THEN 1 ELSE 0 END) AS MALE_PATIENTS, 
    SUM(CASE WHEN GENDER = 'F' THEN 1 ELSE 0 END) AS FEMALE_PATIENTS, 
    ROUND(100 * SUM(CASE WHEN MARITAL_STATUS = 'M' AND ETHNICITY = 'nonhispanic' THEN 1 ELSE 0 END) / COUNT(*)) AS NON_HISPANIC_MARRIED_PERCENTAGE 
  FROM 
    vrm32.MITRE_PATIENT p 
    INNER JOIN vrm32.MITRE_PATIENT_IMMUNIZATION i ON p.PATIENT_ID = i.PATIENT_ID 
  WHERE 
    COUNTY = 'Middlesex County' 
    AND IMMUNIZATION_CODE IN ('52', '43', '83', '8') 
  GROUP BY 
    RACE) Q1,
  (SELECT M.RACE, M.MEDICATION_CODE, SUBSTR(M.MEDICATION_DESCRIPTION, 1, INSTR(M.MEDICATION_DESCRIPTION, ' ') - 1) AS MEDICATION_NAME, M.TOTAL_COST AS HIGHEST_TOTAL_COST
FROM (
    SELECT 
        P.RACE, 
        MED.MEDICATION_CODE,
        MED.MEDICATION_DESCRIPTION,
        SUM(MED.TOTAL_COST) AS TOTAL_COST
    FROM vrm32.MITRE_PATIENT P
    JOIN vrm32.MITRE_PATIENT_MEDICATION MED ON MED.PATIENT_ID = P.PATIENT_ID
    JOIN vrm32.MITRE_PATIENT_IMMUNIZATION IMM ON IMM.PATIENT_ID = P.PATIENT_ID
    WHERE P.COUNTY = 'Middlesex County'
        AND IMM.IMMUNIZATION_CODE IN ('52', '43', '83', '8')
    GROUP BY P.RACE, MED.MEDICATION_CODE, MED.MEDICATION_DESCRIPTION
) M
JOIN (
    SELECT RACE, MAX(TOTAL_COST) AS MAX_TOTAL_COST
    FROM (
        SELECT 
            P.RACE, 
            MED.MEDICATION_CODE,
            SUM(MED.TOTAL_COST) AS TOTAL_COST
        FROM vrm32.MITRE_PATIENT P
        JOIN vrm32.MITRE_PATIENT_MEDICATION MED ON MED.PATIENT_ID = P.PATIENT_ID
        JOIN vrm32.MITRE_PATIENT_IMMUNIZATION IMM ON IMM.PATIENT_ID = P.PATIENT_ID
        WHERE P.COUNTY = 'Middlesex County'
            AND IMM.IMMUNIZATION_CODE IN ('52', '43', '83', '8')
        GROUP BY P.RACE, MED.MEDICATION_CODE
    ) C
    GROUP BY RACE
) T ON M.RACE = T.RACE AND M.TOTAL_COST = T.MAX_TOTAL_COST) Q2,
 
(SELECT
    p.RACE,
    pr.REASON_CODE,
    pr.REASON_DESCRIPTION,
    SUM(pr.BASE_COST) AS TOTAL_BASE_COST
FROM
    vrm32.MITRE_PATIENT p
    JOIN vrm32.MITRE_PATIENT_PROCEDURE pr ON p.PATIENT_ID = pr.PATIENT_ID
WHERE
    p.COUNTY = 'Middlesex County'
    AND p.RACE IS NOT NULL
    AND p.GENDER IS NOT NULL
    AND p.PATIENT_ID IN (
        SELECT i.PATIENT_ID
        FROM vrm32.MITRE_PATIENT_IMMUNIZATION i
        WHERE i.IMMUNIZATION_CODE IN ('52', '43', '83', '8')
    )
    AND pr.REASON_DESCRIPTION NOT LIKE '%pregnancy%'
GROUP BY
    p.RACE,
    pr.REASON_CODE,
    pr.REASON_DESCRIPTION
HAVING
    SUM(pr.BASE_COST) = (
        SELECT MAX(total_base_cost)
        FROM (
            SELECT
                p.RACE,
                pr.REASON_CODE,
                pr.REASON_DESCRIPTION,
                SUM(pr.BASE_COST) AS total_base_cost
            FROM
                vrm32.MITRE_PATIENT p
                JOIN vrm32.MITRE_PATIENT_PROCEDURE pr ON p.PATIENT_ID = pr.PATIENT_ID
            WHERE
                p.COUNTY = 'Middlesex County'
                AND p.RACE IS NOT NULL
                AND p.GENDER IS NOT NULL
                AND p.PATIENT_ID IN (
                    SELECT i.PATIENT_ID
                    FROM vrm32.MITRE_PATIENT_IMMUNIZATION i
                    WHERE i.IMMUNIZATION_CODE IN ('52', '43', '83', '8')
                )
                AND pr.REASON_DESCRIPTION NOT LIKE '%pregnancy%'
            GROUP BY
                p.RACE,
                pr.REASON_CODE,
                pr.REASON_DESCRIPTION
        )
        WHERE
            RACE = p.RACE
    )
ORDER BY
    p.RACE ASC,
    TOTAL_BASE_COST DESC) Q3;

 

-- SQL (NITRE):	

SELECT 
  NR.RACE_DESCRIPTION,
  COUNT(*) AS TOTAL_PATIENTS,
  SUM(CASE WHEN P.GENDER_ID = 'M' THEN 1 ELSE 0 END) AS MALE_PATIENTS,
  SUM(CASE WHEN P.GENDER_ID = 'F' THEN 1 ELSE 0 END) AS FEMALE_PATIENTS,
  ROUND(100 * SUM(CASE WHEN P.MARITAL_STATUS_ID = 'M' AND P.ETHNICITY_ID = 'nonhispanic' THEN 1 ELSE 0 END) / COUNT(*)) AS NON_HISPANIC_MARRIED_PERCENTAGE,
  M.MEDICATION_CODE,
  SUBSTR(M.MEDICATION_DESCRIPTION, 1, INSTR(M.MEDICATION_DESCRIPTION, ' ') - 1) AS MEDICATION_NAME,
  M.TOTAL_COST AS HIGHEST_TOTAL_COST
FROM vrm32.NITRE_PATIENT P
JOIN vrm32.NITRE_PATIENT_IMMUNIZATION IMM ON IMM.PATIENT_ID = P.PATIENT_ID
JOIN vrm32.NITRE_PATIENT_MEDICATION MED ON MED.PATIENT_ID = P.PATIENT_ID
JOIN vrm32.NITRE_MEDICATION MD ON MED.MEDICATION_CODE = MD.MEDICATION_CODE
JOIN vrm32.NITRE_CITY nc ON p.LIVING_PLACE_COUNTRY_ID = nc.COUNTRY_ID
JOIN vrm32.NITRE_COUNTY co ON nc.COUNTY_ID = co.COUNTY_ID
JOIN vrm32.NITRE_RACE NR ON P.RACE_ID = NR.RACE_ID
LEFT JOIN (
  SELECT 
    NR.RACE_DESCRIPTION, 
    MED.MEDICATION_CODE,
    MD.MEDICATION_DESCRIPTION,
    SUM(MED.TOTAL_COST) AS TOTAL_COST
  FROM vrm32.NITRE_PATIENT P
  JOIN vrm32.NITRE_PATIENT_MEDICATION MED ON MED.PATIENT_ID = P.PATIENT_ID
  JOIN vrm32.NITRE_PATIENT_IMMUNIZATION IMM ON IMM.PATIENT_ID = P.PATIENT_ID
  JOIN vrm32.NITRE_CITY nc ON p.LIVING_PLACE_COUNTRY_ID = nc.COUNTRY_ID
  JOIN vrm32.NITRE_MEDICATION MD ON MED.MEDICATION_CODE = MD.MEDICATION_CODE
  JOIN vrm32.NITRE_RACE NR ON P.RACE_ID = NR.RACE_ID
  JOIN vrm32.NITRE_COUNTY co ON nc.COUNTY_ID = co.COUNTY_ID
  WHERE co.COUNTY_ID = 9
    AND IMM.IMMUNIZATION_CODE IN ('52', '43', '83', '8')
  GROUP BY NR.RACE_DESCRIPTION, MED.MEDICATION_CODE, MD.MEDICATION_DESCRIPTION
) M ON NR.RACE_DESCRIPTION = M.RACE_DESCRIPTION
JOIN (
  SELECT 
    RACE_DESCRIPTION, 
    MAX(TOTAL_COST) AS MAX_TOTAL_COST
  FROM (
    SELECT 
      NR.RACE_DESCRIPTION, 
      MED.MEDICATION_CODE,
      SUM(MED.TOTAL_COST) AS TOTAL_COST
    FROM vrm32.NITRE_PATIENT P
    JOIN vrm32.NITRE_PATIENT_MEDICATION MED ON MED.PATIENT_ID = P.PATIENT_ID
    JOIN vrm32.NITRE_PATIENT_IMMUNIZATION IMM ON IMM.PATIENT_ID = P.PATIENT_ID
    JOIN vrm32.NITRE_RACE NR ON P.RACE_ID = NR.RACE_ID
    JOIN vrm32.NITRE_CITY nc ON p.LIVING_PLACE_COUNTRY_ID = nc.COUNTRY_ID
    JOIN vrm32.NITRE_COUNTY co ON nc.COUNTY_ID = co.COUNTY_ID
    WHERE co.COUNTY_ID = 9
      AND IMM.IMMUNIZATION_CODE IN ('52', '43', '83', '8')
    GROUP BY NR.RACE_DESCRIPTION, MED.MEDICATION_CODE
  ) C
  GROUP BY RACE_DESCRIPTION
) T ON NR.RACE_DESCRIPTION = T.RACE_DESCRIPTION AND M.TOTAL_COST = T.MAX_TOTAL_COST
WHERE co.COUNTY_ID = 9
  AND IMM.IMMUNIZATION_CODE IN ('52', '43', '83', '8')
GROUP BY 
  NR.RACE_DESCRIPTION, 
  M.MEDICATION_CODE, 
  M.MEDICATION_DESCRIPTION, 
  M.TOTAL_COST,
  T.RACE_DESCRIPTION;
  



